replacer.blabla = {}
replacer.blabla.log = "[replacer] %s: %s"
replacer.blabla.mode_single = "Replace single node."
replacer.blabla.mode_field = "Left click: Replace field of nodes of a kind where a translucent node is in front of it. Right click: Replace field of air where no translucent node is behind the air."
replacer.blabla.mode_crust = "Left click: Replace nodes which touch another one of its kind and a translucent node, e.g. air. Right click: Replace air nodes which touch the crust"
replacer.blabla.mode_chunkborder = "TODO: chunkborder"

replacer.blabla.protected_at = "Protected at %s"
replacer.blabla.blacklisted = 'Replacing nodes of type "%s" is not allowed on this server. Replacement failed.'
replacer.blabla.run_out = 'You have no further "%s". Replacement failed.'
replacer.blabla.attempt_unknown_replace = 'Unknown node: "%s"'
replacer.blabla.attempt_unknown_place = 'Unknown node to place: "%s"'
replacer.blabla.can_not_dig = 'Could not dig "%s" properly.'
replacer.blabla.can_not_place = 'Could not place "%s".'
replacer.blabla.not_a_node = 'Error: "%s" is not a node.'
replacer.blabla.wait_for_load = "Target node not yet loaded. Please wait a moment for the server to catch up."
replacer.blabla.nothing_to_replace = "Nothing to replace."
replacer.blabla.need_more_charge = "Not enough charge to use this mode."
replacer.blabla.too_many_nodes_detected = "Aborted, too many nodes detected."
replacer.blabla.charge_required = "Need %d charge to replace %d nodes."
replacer.blabla.count_replaced = "%s nodes replaced."
replacer.blabla.mode_changed = "Mode changed to %s: %s"
replacer.blabla.none_selected = "Error: No node selected."
replacer.blabla.not_in_creative = 'Item not in creative invenotry: "%s".'
replacer.blabla.not_in_inventory = 'Item not in your inventory: "%s".'
replacer.blabla.set_to = 'Node replacement tool set to: "%s".'
replacer.blabla.description_basic = "Node replacement tool"
replacer.blabla.description_technic = "Node replacement tool (technic)"

